### ISSUE TITLE
Computing embeddings/scores with LENS

### ISSUE THREAD

**Issue by jacobwjs** [ContextualAI/lens#2]
Hi thanks for the great work. Very interested to see where LENS goes.

I want to use LENS to annotate a few datasets, and need to measure image, text similarities where text will come from an external LLM. 

Any plans to extend Lens class to expose the embedding model to do this? Currently I'm writing a wrapper around the already allocated CLIP model, but would like to abstract away.

Something along the lines of,
```python
image = some_pil_image
text = [text_a, text_b, ...]
scores, _, _ = Lens.encode(
    image=image,
    text=text,
    sorted=True
)
```

**Comment by williamberrios** [comment]
Thanks, @jacobwjs for your interest in LENS, unfortunately is not in our current plans. Feel free to work on the wrapper and open a PR.

**Comment by bilal-aamer** [comment]
@jacobwjs Are you still working on the wrapper?

**Comment by jacobwjs** [comment]
I did implement something. What would you like to know?

**Comment by bilal-aamer** [comment]
Would love to contribute and build using and on it.
